### ISSUE TITLE
Citation Count Mismatch

### ISSUE THREAD

**Issue by CameronDevine** [MicrosoftDocs/microsoft-academic-services#139]
Using the Project Academic Knowledge API with the evaluate query `Id=2141775109` returns the `CC` attribute showing that this paper has been cited 229 times. However, the evaluate query `RId=2141775109` returns only 228 papers. Why is this happening?

The papers with IDs 1990351237 and 2322584079 have the same issue, with the latter having 13 more citations according to the `CC` attribute then found using the `RId` query.

**Comment by CameronDevine** [comment]
@DarrinEide Do you know why this is happening?

**Comment by alch-msft** [comment]
Hi CameronDevine,

I cannot re-produce the issue you described. Id=2141775109 returns 125 citations and RId=2141775109 returns the same amount. Can you provide the full API request/response and the request date? 

Alvin
