### ISSUE TITLE
Not all Journal attributes available

### ISSUE THREAD

**Issue by costinBol** [MicrosoftDocs/microsoft-academic-services#141]
When viewing a Journal on the Microsoft Academic website (e.g. https://academic.microsoft.com/journal/176903982 ), we have some attributes not avaialble through the API:
- About
- Website Links
- Related Journals
- Related Topics

These are not included in the documentation.

**Comment by alch-msft** [comment]
Thanks costinBol.  You should be able to find these detailed information can be found in Microsoft Academic Graph, which is the raw content for Project Academic Knowledge API and Microsoft Academic Knowledge Exploration Service
