### ISSUE TITLE
Interpret for DOI seems broken

### ISSUE THREAD

**Issue by costinBol** [MicrosoftDocs/microsoft-academic-services#145]
1. Run interpret with query 10.1016/j.ahj.2016.10.011
2. Check suggestions: 

{
  "query": "doi 10.1016/j.ahj.2016.10.011",
  "interpretations": [{
    "logprob": -40.999,
    "parse": "<rule name=\"#GetPapers\"><attr name=\"academic#F.FN\" canonical=\"diffusion of innovations\">doi</attr> 10.1016/j.ahj.2016.10.011</rule>",
    "rules": [{
      "name": "#GetPapers",
      "output": {
        "type": "query",
        "value": "Composite(F.FN=='diffusion of innovations')"
      }
    }]
  }, {
    "logprob": -42.631,
    "parse": "<rule name=\"#GetPapers\"><attr name=\"academic#W\">doi</attr> 10.1016/j.ahj.2016.10.011</rule>",
    "rules": [{
      "name": "#GetPapers",
      "output": {
        "type": "query",
        "value": "W='doi'"
      }
    }]

**Comment by costinBol** [comment]
Also, Evaluate by DOI seems broken as well: 
GET https://api.labs.cognitive.microsoft.com/academic/v1.0/evaluate?expr=DOI='10.1093/eurheartj/ehw099'&model=latest&count=10&offset=0&attributes=Id,Ti,Ty HTTP/1.1

**Comment by DarrinEide** [comment]
DOI must be provided with all uppercase letters when using Evaluate/CalcHistogram per https://docs.microsoft.com/en-us/academic-services/project-academic-knowledge/reference-paper-entity-attributes, however there does seem to be a regression in Interpret. 

Pushing hotfix for this in our next release. Thank you for raising awareness!

**Comment by DarrinEide** [comment]
This has been resolved.
